M48
; DRILL file {KiCad 9.0.5} date 2026-02-01T07:57:11-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-01T07:57:11-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.300
%
G90
G05
T1
X4.5Y-4.04
X4.5Y-6.58
X4.5Y-9.12
X4.5Y-11.66
T2
X29.0Y-2.92
X29.0Y-8.0
X29.0Y-13.08
M30
