M48
; DRILL file {KiCad (6.0.7)} date Wed Jan 18 19:03:09 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-18T19:03:09-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X-0.15Y0.2
X-0.15Y0.1
X0.0Y0.1
X0.0Y0.0
X0.0Y-0.1
T0
M30
