M48
; DRILL file {KiCad 7.0.7} date Sat Dec 16 19:35:20 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-16T19:35:20-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0433
%
G90
G05
T1
X0.15Y-0.35
X0.25Y-0.35
X0.35Y-0.35
T2
X0.125Y-0.15
X0.225Y-0.15
X0.325Y-0.15
T0
M30
